export { default as ContactApp } from './ContactApp/ContactApp'
export { default as Landing } from './Landing/Landing'
export { default as Login } from './Login/Login'
export { default as Register } from './Register/Register'
export { default as NotFound } from './NotFound'
