export const Contacts = [
  {
    id: 1,
    name: "Wilmer",
    lastname: "Rodriguez",
    birth: "08/03/1999",
    phone: 987658789,
    image: "",
    email: "wilmer@gmail.com",
    company: "BorisCompany",
    address: "San miguel",
    website: "wilmer.com",
    customField: "Campo de prueba",
    dataCustomField: "No se xd",
  },
  {
    id: 2,
    name: "Wilmer",
    lastname: "Rodriguez",
    birth: "08/03/1999",
    phone: 987658789,
    image: "",
    email: "wilmer@gmail.com",
    company: "BorisCompany",
    address: "San miguel",
    website: "wilmer.com",
    customField: "Campo de prueba",
    dataCustomField: "No se xd",
  },
  {
    id: 3,
    name: "Wilmer",
    lastname: "Rodriguez",
    birth: "08/03/1999",
    phone: 987658789,
    image: "",
    email: "wilmer@gmail.com",
    company: "BorisCompany",
    address: "San miguel",
    website: "wilmer.com",
    customField: "Campo de prueba",
    dataCustomField: "No se xd",
  },
  
  
];
